apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend-lb
  namespace: longhorn-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.211
  selector:
    app: longhorn-ui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
