apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-alerts
  namespace: monitoring

spec:
  refreshInterval: 48h

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: telegram-alerts

  data:
    - secretKey: bot-token
      remoteRef:
        key: telegram-bot-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    - secretKey: chat-id
      remoteRef:
        key: telegram-chat-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
