global:
  domain: argocd.homelab.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.178.213
    annotations:
      metallb.universe.tf/address-pool: homelab-pool

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  enabled: true

notifications:
  enabled: false

dex:
  enabled: false

redis:
  enabled: true