apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: homelab-platform

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.10.0   # pinned from live release (helm list -n logging)
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/ali-fathi/devops-homelab/main/kubernetes/observability/logging/alloy-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
