apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshotter
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab-platform
    app.kubernetes.io/component: storage
spec:
  project: homelab-platform

  source:
    repoURL: https://github.com/ali-fathi/devops-homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/csi-snapshotter

    directory:
      include: "{*.yaml,*.yml}"
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
