apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-config
  namespace: argocd
spec:
  project: homelab-platform

  source:
    repoURL: https://github.com/ali-fathi/devops-homelab.git
    targetRevision: main
    path: kubernetes/observability/config

    directory:
      include: "{*.yaml,*.yml}"
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
