grafana:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 30d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 5Gi
