apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-data
  namespace: ring-health
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/part-of: ring-health-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
