apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: ring-health
  labels:
    app.kubernetes.io/name: victoriametrics
    app.kubernetes.io/part-of: ring-health-tracker
  annotations:
    metallb.universe.tf/address-pool: homelab-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.214

  selector:
    app.kubernetes.io/name: victoriametrics

  ports:
    - name: http
      port: 8428
      targetPort: http
