alertmanager:
  enabled: true

  alertmanagerSpec:
    secrets:
      - telegram-alerts

  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: "null"

      group_by:
        - alertname
        - severity

      group_wait: 1m
      group_interval: 15m
      repeat_interval: 24h

      routes:
        - matchers:
            - alertname="Watchdog"
          receiver: "null"

        - matchers:
            - severity="critical"
          receiver: telegram
          continue: false

    receivers:
      - name: telegram
        telegram_configs:
          - api_url: https://api.telegram.org
            bot_token_file: /etc/alertmanager/secrets/telegram-alerts/bot-token
            chat_id: 84899032
            send_resolved: false
            parse_mode: HTML

      - name: "null"